name: CI

on:
  push:
    branches:
    - trigger
  schedule:
  - cron: '0 0 * * *'
  repository_dispatch: {}

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Write README.md
      run: |
        echo Hello World >> README.md
    - uses: bumfo/push-workspace@v1-release
      with:
        ref: 'refs/heads/dist'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
