name: CI

on:
  push:
    branches:
    - trigger
  schedule:
  - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Say hello world
      run: echo Hello, world!
